### ISSUE TITLE
How to create chrome extension button within page

### ISSUE THREAD

**Issue by Germminate** [judell/controlling-a-browser-extension-with-puppeteer#1]
Hi Judell,

This was a very useful repo and it helped me greatly.

However, after looking through all the scripts, I don't see where the button (at the top left of the page) is created within your scripts. Could you point me to it?

I would like to create a button within a page for an extension I use as well, to automate the process.

**Comment by judell** [comment]
Hi Germaine,

Please see:

https://github.com/judell/controlling-a-browser-extension-with-puppeteer/blob/master/browser-extension/start.js#L22

https://github.com/judell/controlling-a-browser-extension-with-puppeteer/blob/master/browser-extension/main.js#L8

**Comment by Germminate** [comment]
Hi Judell, 
sorry i wasn't clear in the post, i meant to ask, how is it inserted on installation? 

my extension has the same functions as what you have in your start.js and main.js, but it only adds a button in the extensions bar, not a button within the page like yours does.
